; Configuration de Forma Dock

[window]
; Taille initiale de la fenêtre (en pixels)
width = 550
height = 560

; Taille minimale (évite une fenêtre inutilisable)
min_width = 320
min_height = 280

; Position initiale de la fenêtre sur l'écran (pixels)
; x = 100
; y = 100


; Transparence de la fenêtre (vrai/faux, 1/0, yes/no)
transparent = true

; Décorations natives Windows (true = barre de titre classique)
decorations = false

; Opacité de l'interface (0 à 100)
; 0 = totalement transparent, 100 = opaque comme avant
opacity = 5

; Couleur de fond (format #RRGGBB ou R,G,B)
bg_color = #0E1018

; Rayon des coins en pixels (0 à 40)
corner_radius = 0

[icons]
; Taille d’icône par défaut (entre 32 et 512)
size_px = 118